# create a list using user input
L1 = []
fruit1 = input("enter the name of fruit:")
L1.append(fruit1)
fruit2 = input("enter the name of fruit:")
L1.append(fruit2)
fruit3 = input("enter the name of fruit:")
L1.append(fruit3)
fruit4 = input("enter the name of fruit:")
L1.append(fruit4)
fruit5 = input("enter the name of fruit:")
L1.append(fruit5)
fruit6 = input("enter the name of fruit:")
L1.append(fruit6)
fruit7 = input("enter the name of fruit:")
L1.append(fruit7)
fruit8 = input("enter the name of fruit:")
L1.append(fruit8)
print(L1)